### ISSUE TITLE
Create official docker image

### ISSUE THREAD

**Issue by BeatLink** [etesync/etesync-web#125]
Perhaps you could create an official docker build and upload it to docker hub? That would make self hosting installation extremely easy. Docker also provides a consistent runtime environment so environment related bugs would be reduced as well

**Comment by tasn** [comment]
The web client is client-side only. It's just a few HTML, JavaScript and etc files that can be served by any server, including easily (locally) by running `python -m http.server PORT`. A docker is thus an overkill for this because there really isn't anything in the environment.

We could potentially offer an archive of the generated HTML/JS/CSS, though it would really just be what's already at https://client.etesync.com 

What are your thoughts? What in particular did you try doing that you struggled with?

**Comment by BeatLink** [comment]
Hmm fair enough. Basically i wanted a quick and easy way to download and install the web client. The biggest problem was setting up yarn for me. A docker image with yarn preinstalled would make that drastically easier. There are already docker images for etesync-web on hub.docker.com. I was merely asking for an official version. Maybe it could be based on one of those existing images even!

**Comment by tasn** [comment]
It's now available for download at https://client.etesync.com/etesync-web.tgz and then you just serve it as normal HTML files using your favourite web server.

**Comment by BeatLink** [comment]
ahh okay. Thanks!

**Comment by tasn** [comment]
Does that solve your issue?

**Comment by BeatLink** [comment]
Ive decided to just use client.etesync.com. One less service for my server to maintain :). Ill use it tho if i decide to fully self host everything tho!

**Comment by tasn** [comment]
Great. :)
