### ISSUE TITLE
Hosted DAV Adapter gives 500

### ISSUE THREAD

**Issue by BrechtSerckx** [etesync/etesync-web#175]
When trying to re-enable the Hosted DAV adapter after migrating to V2, it gives a 500.

Steps taken:
1. Go to the [Hosted DAV Adapter](https://dashboard.etebase.com/user/partner/etesync/hosted-dav/)
2. Click `Enable`
3. Wait a bit
4. An error is displayed: `500 Server Error: Internal Server Error for url: https://dav.etesync.com/api/v1/creds/`

Browser: Firefox 78
OS: Linux/NixOS 20.03
User-Agent: `Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0`

**Comment by tasn** [comment]
Yeah, we are on it. :)
Thanks for reporting!

**Comment by tasn** [comment]
Fixed.

**Comment by stefanschramek** [comment]
Hi,
I have the same issues after disabling and re-enabling the feature!
Can you please take a look in this?

Thanks
Stefan

**Comment by tasn** [comment]
What's going on exactly for you?

**Comment by stefanschramek** [comment]
Actually im trying to find the best way to prepare a bunch of vcf-files for import.
So I imported the same file several times and recreated the contacts-collection at the same time to give it a fresh start.
I wanted to connect my iPhone without using the App via DAV adapter.
Unfortunately the contacts seems to be cached, as some changes in following uploads are not reflected.
I tried to figure out if this is caused by the DAV adapter or the iPhone. So I disabled and re-enabled it.
Now the login is not working with the new password that was generated - and I only see "A server error occurred.  Please contact the administrator." in the web browser"!
