### ISSUE TITLE
Is there a way to set the REACT_APP_DEFAULT_API_PATH with the prebuilt tarball without needing to build?

### ISSUE THREAD

**Issue by BeatLink** [etesync/etesync-web#184]

**Comment by tasn** [comment]
I don't think so. You can potentially find the value that's there and use `sed` to replace it. A bit fragile, but could work. Though the JS app is just a static pre-built JS app, so you can't pass it any parameters on runtime.

**Comment by Ezwen** [comment]
Sorry to "up" this closed issue, but I just wanted to suggest to try to find a way to allow users to change `REACT_APP_DEFAULT_API_PATH` without having to re-build the application. For instance, could this environment variable be read at run-time instead of build-time? This would facilitate self-hosting greatly.

**Comment by tasn** [comment]
There are no env vars during runtime. It's static HTML + JS files that are generated on build. Though I don't think it's that big of an issue, it just adds an extra step of clicking "advanced" and choosing a different server.
