### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by 2br-2b** [etesync/etesync-web#199]
When using the week view on my calendar, it seems to be displaying all of the times in some other time zone (I assume UTC). In addition, when creating a task, the default time zone is always UTC.

It would be useful if these could update to match the time zone of the user.

**Comment by tasn** [comment]
Timezone works and already uses the local one. If it's not the case for you, it's 99% likely because you are using some privacy extension that spoofs your timezone to UTC to reduce fingerprinting. I'm closing it as I bet this is what's going on.
If it's not the case, please reopen the ticket and we can take a better look.
