### ISSUE TITLE
[Feature] Instant export capability (requirement of GDPR)

### ISSUE THREAD

**Issue by ajvsol** [etesync/etesync-web#30]
I read your FAQ and it mentioned that there was no way to export your data except on email request, which violates [article 20.1.B](https://gdpr-info.eu/art-20-gdpr/) of the GDPR (requires automated export). It also seems your servers are hosted in Austria.

Personally I'd also like the feature because I want to use your SaaS, but without being able to export on demand I can't trust it fully unfortunately.

**Comment by tasn** [comment]
Hey,

Thanks for pointing out it lacks an explanation on how to export the raw data. We assumed most people wanted to access the decrypted data so we provided information for that, but I guess there may be cases where people would want to download the raw (encrypted) data as we save it, so I added explanation for that too. I also clarified the text a bit in other areas. The update will go online within a few days, hopefully by the end of the weekend.

Let me additionally clarify one thing though: automated export has always been possible and never needed our intervention. The wording was as such just so we can assist users. Additionally, in the FAQ, the paragraph about "automated export tool" was describing something else, it's just unfortunate that it used the same wording as the GDPR. The wording there was about automatically downloading the data from your account using a script (that you can run automatically), rather than from the website, and anyhow, it was also outdated, as this has been implemented for at least a year now.

Here's the text as it'll read after the update is pushed:

> 
> <div class="answer">
>     <p>
>     Exporting your data is easy! Either setup <a href="{% surl 'etesync-dav' %}">EteSync-DAV</a> and use the web UI for a full export of your data, or use an Android app that supports exporting, such as <a href="https://play.google.com/store/apps/details?id=com.google.android.contacts&hl=en_GB">Google Contacts</a> and <a href="https://play.google.com/store/apps/details?id=org.sufficientlysecure.ical">Calendar Import - Export</a>.
>     Additionally, you can just download the data as we have it, in
>     raw form (encrypted), by accessing the <a href="https://www.etesync.com/api/v1/">browsable API explorer</a>
>     and downloading the parts that you'd like exported.
>     </p>
>     <div>
>     You will probably want to take especially take a look at:
>       <ul>
>         <li>
>           <a href="https://www.etesync.com/api/v1/journals/">The journal list</a>
>         </li>
>         <li>
>           <a href="https://www.etesync.com/api/v1/journals/JOURNAL_UID/entries/">Per-journal entries list</a> where you'd need to replace JOURNAL_UID with the relevant journal UID.
>         </li>
>       </ul>
>     </div>
>     <p>
>     If you are looking for a tool to automatically download your data
>     to your computer (encrypted or not), e.g. for backup purposes,
>     you can just use the example script from <a href="{% surl 'pyetesync' %}">the Python API repository</a>.
>     </p>
>     <p>
>     In addition, please remember that our slogan is
>     <q>Your Data, Yours Only</q>. Your data is yours, and we will
>     always have a way to export your data, so just reach out if you
>     have any more questions.
>     </p>
> </div>


I hope this clarifies things, and thanks again for bringing it to my attention!

I'm closing this ticket as it's not an issue, and the clarifications have been committed and will be uploaded in the next few days. Please don't hesitate to re-open it if you think the issue has not been resolved.

All the best,
Tom
