### ISSUE TITLE
Can not setup new sync account after deleting old account

### ISSUE THREAD

**Issue by brainskan** [etesync/etesync-web#68]
I can not seem to setup a new sync account on Android (Samsung Galaxy S9+). I keep getting the following error after entering my login account username and password. I get past that. Then it asks me to setup a new encryption password. That is when it throws this error (see attached screenshot with code)

![error_code](https://user-images.githubusercontent.com/36638960/70936676-cc74e580-2010-11ea-8c95-1a0a48f33d9a.jpg)

My login account username and password are correct. I can log in fine on the web to check my account. I am using Lastpass password manager to automatically fill in the fields, so it can't be a typing error. It works fine on the web, and looks fine when on my phone. I turn off the visual password masking so that I can inspect the passwords and verify they are correct.

I have been using the service fine since April 2019. Just recently in the past week, I noticed that Task and Calendar apps were no longer syncing. So I started troubleshooting: logging out and back in. It would not accept encryption passwords I had on hand. I tried setting up a new account to sync. That's when I got the error.

I deleted my original sync account through the Android app. I uninstalled EteSync, rebooted the phone, and reinstalled the app again from the Google Play store.

I don't even care at this point about recovering my old info. I can not setup a new sync account. It will not let me establish a new encryption password. I still have to use my original email and account password that I used to setup the original account because that is where my paid version is registered.

**Comment by tasn** [comment]
This is the wrong repo for this issue, the correct one would be in https://github.com/etesync/android/issues/ as it's an Android issue.

With that being said, I replied to your email, and since I don't think it's a bug it would make more sense to discuss it there. If you prefer discussing on Github please open a ticket in the Android repo (as mentioned above).

For posterity:
1. Resetting the account to start from scratch is easy, you just need to contact me/support to do that.
2. Emails are unfortunately case sensitive (per the standard) and EteSync's encryption key is unfortunately salted with the email (as entered) which means this error can happen if the email was entered differently than how it was when the account was created.

**Comment by brainskan** [comment]
Fair enough. Thanks for responding. I will email support for a reset from scratch.

**Comment by tasn** [comment]
It shouldn't be needed though... It's just an easy option. I wonder what went on in your case to have caused this... :|
