### ISSUE TITLE
Feature request: change date and time picker

### ISSUE THREAD

**Issue by davidwisniewski** [etesync/etesync-web#9]
The current date and time picker is pretty clunky. Picking the day is fine, I can just select it from a calendar. But in order to pick a start and end time, I need to scroll through hours and minutes every time. 
It would help if e.g. there would be a default duration at least (1h?), so that if I pick the start time, the end time is added automatically. Or, give the option to type in date and time manually with the keyboard, which would be faster. Even better, switch to a different time picker that is more intuitive to use (e.g. clock icon).

**Comment by tasn** [comment]
Thanks for reporting this.
The current date and time picker is horrible. It's pretty bad on mobile, and horrific on the desktop. I'd love to change it back to the native pickers in browsers, but unfortunately they don't work well on all
browsers, which is why I changed it to this in the first place. I know it needs to be changed.

Would need to take a second look into using the native browser picker and having this as a fallback.

**Comment by rugk** [comment]
Hmm, [about 80%](https://caniuse.com/#feat=input-datetime), but Firefox does not support combinations (only date or time) – maybe just use two input fields?

**Comment by tasn** [comment]
@rugk, it was actually 2 input fields because of Firefox's poor support. Though I don't remember who reported it, but the problem was another browser. Maybe Chrome mobile, I'm not sure...

**Comment by tasn** [comment]
@Tal-Leibman, maybe this is also of interest? I can't believe it took me so long to revisit this. :| Sorry everyone.
